// <auto-generated />
using System;
using System.Collections.Generic;
using FileService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(FileServiceDbContext))]
    [Migration("20260323083610_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Domain.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Owner", "FileService.Domain.MediaAsset.Owner#MediaOwner", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Context")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("context");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("entity_id");
                        });

                    b.HasKey("Id")
                        .HasName("pk_media_asset_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_media_assets_status_created_at");

                    b.ToTable("media_assets", (string)null);

                    b.HasDiscriminator<string>("AssetType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FileService.Domain.PreviewAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.MediaAsset");

                    b.HasDiscriminator().HasValue("Preview");
                });

            modelBuilder.Entity("FileService.Domain.VideoAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.MediaAsset");

                    b.HasDiscriminator().HasValue("Video");
                });

            modelBuilder.Entity("FileService.Domain.MediaAsset", b =>
                {
                    b.OwnsOne("FileService.Domain.StorageKey", "FinalKey", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasJsonPropertyName("key");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasJsonPropertyName("location");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasJsonPropertyName("prefix");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets");

                            b1
                                .ToJson("final_key")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsOne("FileService.Domain.StorageKey", "Key", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasJsonPropertyName("key");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasJsonPropertyName("location");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasJsonPropertyName("prefix");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets");

                            b1
                                .ToJson("key")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsOne("FileService.Domain.MediaData", "MediaData", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId");

                            b1.Property<int>("ExpectedChunksCount")
                                .HasJsonPropertyName("expected_chunks_count");

                            b1.Property<long>("Size")
                                .HasJsonPropertyName("size");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets");

                            b1
                                .ToJson("media_data")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("FileService.Domain.ContentType", "ContentType", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId");

                                    b2.Property<string>("Category")
                                        .IsRequired()
                                        .HasJsonPropertyName("category");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasJsonPropertyName("content_type");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FileService.Domain.FileName", "FileName", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId");

                                    b2.Property<string>("Extension")
                                        .IsRequired()
                                        .HasJsonPropertyName("extension");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasJsonPropertyName("name");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.Navigation("ContentType")
                                .IsRequired();

                            b1.Navigation("FileName")
                                .IsRequired();
                        });

                    b.Navigation("FinalKey")
                        .IsRequired();

                    b.Navigation("Key")
                        .IsRequired();

                    b.Navigation("MediaData")
                        .IsRequired();
                });

            modelBuilder.Entity("FileService.Domain.VideoAsset", b =>
                {
                    b.OwnsOne("FileService.Domain.StorageKey", "HlsRootKey", b1 =>
                        {
                            b1.Property<Guid>("VideoAssetId");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasJsonPropertyName("key");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasJsonPropertyName("location");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasJsonPropertyName("prefix");

                            b1.HasKey("VideoAssetId");

                            b1.ToTable("media_assets");

                            b1
                                .ToJson("hls_root_key")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideoAssetId");
                        });

                    b.Navigation("HlsRootKey")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
